version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: impact
      MYSQL_USER: impact
      MYSQL_PASSWORD: impact
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
      - .:/app:ro
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      DB_DSN: "mysql://impact:impact@db:3306/impact"
      APP_ENV: dev
      PLACK_PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: ["./bin/wait-for-db.sh", "&&", "plackup", "-Ilib", "-r", "app.psgi", "-o", "0.0.0.0", "-p", "5000"]

volumes:
  dbdata:
